# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 749309ca052b31eb1a25a3154030fca9613833045c07b2778909b0829c013b172e183907ccb015417e655aa9c3e9562e25450d09a3691832b84d51abe5678feb

test:
  secret_key_base: d1d0986d37f9f16722d9967cab13c2f8380f8753ef2d5179f8841c282a9b7170013c7fde5ad651d01e3f9fdce2ff479d54a36eb1f05849eec896d084316c0776

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d1d0986d37f9f16722d9967cab13c2f8380f8753ef2d5179f8841c282a9b7170013c7fde5ad651d01e3f9fdce2ff479d54a36eb1f05849eec896d084316c0776
